### ISSUE TITLE
LinkSPI compatibility with GBC

### ISSUE THREAD

**Issue by matt-comm-link** [rodri042/gba-link-connection#14]
Hi, I'm doing some research into the idea of using the GBA's gen2 link cable support to allow for cross-generational communications between the GBC and GBA. Your LinkSPI library has me somewhat excited from the fact it uses SPI and a GBC cable but I'm afraid I'm not as well versed in GBA brew as I am the DMG/GBC side of things, and I might be missing something big that'd get in the way of things.

As the person who wrote it are you aware of any pin/protocol compatibility problems I might run in to if I tried to use this library to act as the GBA side of a test of this idea?

**Comment by afska** [comment]
Hi @matt-comm-link,

The documentation says that GBA and GBC are not compatible due to voltage differences, but there are some projects that somehow managed to do this.

Personally, I have zero experience writing GBC homebrew, but `LinkSPI` is just a small wrapper that hides hardware details so I think you'll be able to use it in your project.

**Comment by Anders429** [comment]
An example of a project that does this is here: https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X. There is a video demonstrating the connection working in the README, although I recall there was discussion months ago on the GBA dev discord over whether the voltage differences was unsafe for the hardware or not.

**Comment by matt-comm-link** [comment]
thanks for the link. I'm going to have a good look at this.

**Comment by GearsProgress** [comment]
Apologies for adding to a closed issue, but I'm also trying to do a similar thing with faking a Pokemon trade. From what I can tell, everything looks good besides data being sent in blocks of 32 bits instead of 8 bits. Would changing that be as simple as changing all the 32 bit data sizes to 8 bits (along with changing REG_SIODATA32 to REG_SIODATA8)? Or is there more to it than that?

**Comment by afska** [comment]
@Starport75 you should also set the 8-bit mode (that is, bit 12 of `REG_SIOCNT` = 0). You can take a look to [this unmerged PR](https://github.com/afska/gba-link-connection/pull/8/files) for an example

**Comment by afska** [comment]
@Starport75 I've added a compile-time option to use 8 bit packets in the new v6.2.0 release

**Comment by GearsProgress** [comment]
Oh awesome, that's perfect! Thank you so much for the quick response!!
